# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    bio: Optional[str]
    birthdate: Optional[datetime.date]
