# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: transactions.sql
import dataclasses
import decimal
from typing import AsyncIterator, Iterator, Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from py_sqlc_tester.db import models


COUNT_TRANSACTIONS = """-- name: count_transactions \\:one
SELECT count(*) FROM transactions
"""


CREATE_TRANSACTION = """-- name: create_transaction \\:one
INSERT INTO transactions (
  amount, 
  description
) VALUES (
  :p1, :p2
)
RETURNING id, amount, description, created_at
"""


GET_BALANCE = """-- name: get_balance \\:one
SELECT 
    COALESCE(SUM(amount), 0)\\:\\:NUMERIC(10, 4) AS balance 
FROM transactions
"""


GET_TRANSACTION = """-- name: get_transaction \\:one
SELECT id, amount, description, created_at FROM transactions
WHERE id = :p1 LIMIT 1
"""


SUMMARY_BY_DESCRIPTION = """-- name: summary_by_description \\:many
SELECT
    description,
    SUM(amount)\\:\\:Numeric(10, 4) AS total_amount,
    COUNT(*) AS transaction_count
FROM transactions
GROUP BY description
ORDER BY total_amount DESC
"""


@dataclasses.dataclass()
class SummaryByDescriptionRow:
    description: Optional[str]
    total_amount: decimal.Decimal
    transaction_count: int


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection):
        self._conn = conn

    def count_transactions(self) -> Optional[int]:
        row = self._conn.execute(sqlalchemy.text(COUNT_TRANSACTIONS)).first()
        if row is None:
            return None
        return row[0]

    def create_transaction(self, *, amount: decimal.Decimal, description: Optional[str]) -> Optional[models.Transaction]:
        row = self._conn.execute(sqlalchemy.text(CREATE_TRANSACTION), {"p1": amount, "p2": description}).first()
        if row is None:
            return None
        return models.Transaction(
            id=row[0],
            amount=row[1],
            description=row[2],
            created_at=row[3],
        )

    def get_balance(self) -> Optional[decimal.Decimal]:
        row = self._conn.execute(sqlalchemy.text(GET_BALANCE)).first()
        if row is None:
            return None
        return row[0]

    def get_transaction(self, *, id: int) -> Optional[models.Transaction]:
        row = self._conn.execute(sqlalchemy.text(GET_TRANSACTION), {"p1": id}).first()
        if row is None:
            return None
        return models.Transaction(
            id=row[0],
            amount=row[1],
            description=row[2],
            created_at=row[3],
        )

    def summary_by_description(self) -> Iterator[SummaryByDescriptionRow]:
        result = self._conn.execute(sqlalchemy.text(SUMMARY_BY_DESCRIPTION))
        for row in result:
            yield SummaryByDescriptionRow(
                description=row[0],
                total_amount=row[1],
                transaction_count=row[2],
            )


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def count_transactions(self) -> Optional[int]:
        row = (await self._conn.execute(sqlalchemy.text(COUNT_TRANSACTIONS))).first()
        if row is None:
            return None
        return row[0]

    async def create_transaction(self, *, amount: decimal.Decimal, description: Optional[str]) -> Optional[models.Transaction]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_TRANSACTION), {"p1": amount, "p2": description})).first()
        if row is None:
            return None
        return models.Transaction(
            id=row[0],
            amount=row[1],
            description=row[2],
            created_at=row[3],
        )

    async def get_balance(self) -> Optional[decimal.Decimal]:
        row = (await self._conn.execute(sqlalchemy.text(GET_BALANCE))).first()
        if row is None:
            return None
        return row[0]

    async def get_transaction(self, *, id: int) -> Optional[models.Transaction]:
        row = (await self._conn.execute(sqlalchemy.text(GET_TRANSACTION), {"p1": id})).first()
        if row is None:
            return None
        return models.Transaction(
            id=row[0],
            amount=row[1],
            description=row[2],
            created_at=row[3],
        )

    async def summary_by_description(self) -> AsyncIterator[SummaryByDescriptionRow]:
        result = await self._conn.stream(sqlalchemy.text(SUMMARY_BY_DESCRIPTION))
        async for row in result:
            yield SummaryByDescriptionRow(
                description=row[0],
                total_amount=row[1],
                transaction_count=row[2],
            )
